// Parallel bisect of the serve-mode cross-request nondeterminism.
// READONLY source lanes: no edits, no builds, no GPU, no model runs, no leases.
const EV = 'EVIDENCE: in --serve mode the FIRST request of a fresh process is byte-identical across three fresh processes, but ten identical greedy (temperature 0) requests inside ONE process give 3 different answers. Within-request decode is deterministic. Also established: the adaptive tier in the serve loop is entered with ZERO swaps in flight every time, so the pending race fixed in 958e00a does NOT apply here. Ten identical requests -> 3 distinct answers means what varies is state carried BETWEEN requests. READONLY sources: /home/gostar/Strata (main 0.1.33) and /mnt/gostar_data/strata/worktrees/winprobe (branch feat/window-logits-probe). The serve request loop is in src/program/generate.cpp roughly lines 3970-5660; request start is near 5189; the decode window loop is 5370-5400.';

const out = await runs.all([
  { key: 'sampler', agent: 'scout', task: EV + '\n\nLANE sampler/RNG. Find every place random state is created, seeded, advanced or carried across requests: the sampler and its seed, any engine or host RNG, rejection sampling, top-k/temperature paths, and anything that draws even when temperature is 0 (unconditional draw, tie-break, speculative draft sampling). State whether a per-request SamplerParams or RNG is re-initialised at request start or inherits process-global state, and whether greedy still consumes randomness. Quote file:line, say exactly what carries over, give the minimal fix. Write /mnt/gostar_data/strata/bench/gates-wave24-window-probe/lane-sampler.md.' },
  { key: 'experts', agent: 'scout', task: EV + '\n\nLANE expert cache and PCIe streaming. Examine the expert pool and the residency/host_res tables: which experts are streamed from the host per window, in what order, and whether that ORDER or SET can differ between identical requests. Look at drive, pool_fn/drive_pool_multi/win_pool_fn, drive.d.usage accumulation, the RAM exchange/commit_exchanges path, and any completion-order-dependent work. Also check whether the expert cache is re-sized or re-admitted per request. Quote file:line, rank by likelihood, give the minimal fix. Write /mnt/gostar_data/strata/bench/gates-wave24-window-probe/lane-experts.md.' },
  { key: 'kv', agent: 'scout', task: EV + '\n\nLANE KV state carry-over. Determine what KV/recurrent state survives between requests in serve mode: the QSA ring position, the host copy, the kv-ring restore path, the GDN recurrent state, PLE ple_prev/ple_window, pooled/indexer rows, and the block/ring counters. For each, say whether it is reset at request start or inherits the previous request, and whether any of it can depend on timing (e.g. a stream that has not finished, a non-blocking query deciding residency). Quote file:line, rank by likelihood, minimal fix. Write /mnt/gostar_data/strata/bench/gates-wave24-window-probe/lane-kv.md.' },
  { key: 'mtp', agent: 'scout', task: EV + '\n\nLANE drafter and suffix drafting cross-request state. Examine the MTP drafter (src/core/mtp.cpp, include/strata/core/mtp.hpp) and the serve-mode suffix drafter (strata::spec::SuffixDrafter, DraftPolicy, from_sfx, sfx windows) for state that persists across requests: the coverage ledger, the ring/window, drafted cells, the suffix table, the drafter window histogram, and any policy counters. Say what is reset at request start and what is not, and whether any of it is timing dependent. Quote file:line, rank by likelihood, minimal fix. Write /mnt/gostar_data/strata/bench/gates-wave24-window-probe/lane-mtp.md.' },
  { key: 'reset', agent: 'scout', task: EV + '\n\nLANE request-boundary audit. This is the most direct lane: enumerate EVERY piece of process or session state that a serve request inherits, and check each for a per-request reset. Start where the request loop begins and work to the first decode window. Include counters, flags, the penalty history (hist_n/d_hist), the stage caches, the residency table, any cached allocator or pool, and anything initialised once before the request loop. Produce a checklist table: state, reset at request start yes/no, file:line of the reset or of the absence. Highlight the ones that are NOT reset. Write /mnt/gostar_data/strata/bench/gates-wave24-window-probe/lane-reset.md.' },
]);

for (const r of out) emit({ key: r.key, status: r.status, outputReference: r.outputReference });
emit({ completed: out.filter(r => r.status === 'completed').length, total: out.length });
