// src/kernels/exl3_parity.cpp - CPU EXL3 decode vs the numpy reference fixture (tools/exl3/emit_fixture.py).
//
// Usage: exl3_parity <fixture_dir>
// The fixture is generated by the verified Python specification; a mismatch means this port is wrong.
#include "strata/kernels/cpu/exl3.hpp"

#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <fstream>
#include <string>
#include <vector>

using namespace strata::kernels::cpu;

namespace {

template <typename T>
std::vector<T> read_n(std::istream& in, size_t n) {
    std::vector<T> v(n);
    in.read(reinterpret_cast<char*>(v.data()), (std::streamsize)(n * sizeof(T)));
    return v;
}

float h2f(uint16_t h) {
    uint32_t sign = (uint32_t)(h >> 15) << 31, exp = (h >> 10) & 0x1F, man = h & 0x3FF, f;
    if (exp == 0) {
        if (!man) f = sign;
        else { exp = 127 - 15 + 1; while (!(man & 0x400)) { man <<= 1; --exp; } man &= 0x3FF;
               f = sign | (exp << 23) | (man << 13); }
    } else if (exp == 0x1F) f = sign | 0x7F800000u | (man << 13);
    else f = sign | ((exp + 127 - 15) << 23) | (man << 13);
    float o; std::memcpy(&o, &f, 4); return o;
}

double rel_err(const std::vector<float>& a, const std::vector<float>& b) {
    double num = 0, den = 0;
    for (size_t i = 0; i < b.size(); ++i) { double d = (double)a[i] - b[i]; num += d * d; den += (double)b[i] * b[i]; }
    return std::sqrt(num) / (std::sqrt(den) + 1e-30);
}

}  // namespace

int main(int argc, char** argv) {
    if (argc < 2) { std::fprintf(stderr, "usage: %s <fixture_dir>\n", argv[0]); return 2; }
    std::ifstream in(std::string(argv[1]) + "/exl3_fixture.bin", std::ios::binary);
    if (!in) { std::fprintf(stderr, "cannot open fixture in %s\n", argv[1]); return 77; }

    char magic[4];
    in.read(magic, 4);
    if (std::memcmp(magic, "EXL3", 4) != 0) { std::fprintf(stderr, "bad magic\n"); return 2; }
    int32_t cb_i, ki, nj, bits, tokens, words;
    in.read(reinterpret_cast<char*>(&cb_i), 4); in.read(reinterpret_cast<char*>(&ki), 4);
    in.read(reinterpret_cast<char*>(&nj), 4); in.read(reinterpret_cast<char*>(&bits), 4);
    in.read(reinterpret_cast<char*>(&tokens), 4); in.read(reinterpret_cast<char*>(&words), 4);
    auto cb = (Exl3Codebook)cb_i;
    int k = ki * 16, n = nj * 16;

    auto trellis = read_n<int16_t>(in, (size_t)ki * nj * words);
    auto suh = read_n<uint16_t>(in, k);
    auto svh = read_n<uint16_t>(in, n);
    auto x = read_n<uint16_t>(in, (size_t)tokens * k);
    auto lut_ref = read_n<uint16_t>(in, 1u << 16);
    auto what_ref = read_n<uint16_t>(in, (size_t)k * n);
    auto w_ref_f16 = read_n<uint16_t>(in, (size_t)k * n);
    auto y_ref = read_n<float>(in, (size_t)tokens * n);
    auto w_ref_f32 = read_n<float>(in, (size_t)k * n);
    (void)w_ref_f16;

    int fails = 0;

    // 1) codebook LUT, bit-exact
    std::vector<uint16_t> lut(1u << 16);
    exl3_codebook_lut(cb, lut.data());
    size_t lut_bad = 0;
    for (size_t i = 0; i < lut.size(); ++i) if (lut[i] != lut_ref[i]) ++lut_bad;
    std::printf("codebook LUT: %zu/%zu mismatches\n", lut_bad, lut.size());
    if (lut_bad) ++fails;

    // 2) W_hat decode (window + permutation), bit-exact
    std::vector<uint16_t> what((size_t)k * n);
    exl3_decode_weight_hat((const uint16_t*)trellis.data(), ki, nj, bits, cb, what.data());
    size_t what_bad = 0;
    for (size_t i = 0; i < what.size(); ++i) if (what[i] != what_ref[i]) ++what_bad;
    std::printf("W_hat decode: %zu/%zu mismatches\n", what_bad, what.size());
    if (what_bad) ++fails;

    // 3) reconstruct_weight within fp16 tolerance
    std::vector<uint16_t> w((size_t)k * n);
    exl3_reconstruct_weight((const uint16_t*)trellis.data(), ki, nj, bits, cb, suh.data(), svh.data(),
                            w.data());
    std::vector<float> wf(w.size());
    for (size_t i = 0; i < w.size(); ++i) wf[i] = h2f(w[i]);
    double we = rel_err(wf, w_ref_f32);
    std::printf("reconstruct_weight rel_err: %.3e (limit 3e-2)\n", we);
    if (!(we < 3e-2)) ++fails;

    // 4) folded GEMV within fp32 tolerance
    std::vector<float> y((size_t)tokens * n);
    exl3_folded_gemv((const uint16_t*)trellis.data(), ki, nj, bits, cb, suh.data(), svh.data(),
                     x.data(), tokens, y.data());
    double ye = rel_err(y, y_ref);
    std::printf("folded_gemv rel_err: %.3e (limit 1e-2)\n", ye);
    if (!(ye < 1e-2)) ++fails;

    // 5) ngram ring decode
    int32_t ng_K, ng_dim, ng_hasbias;
    in.read(reinterpret_cast<char*>(&ng_K), 4);
    in.read(reinterpret_cast<char*>(&ng_dim), 4);
    in.read(reinterpret_cast<char*>(&ng_hasbias), 4);
    if (in) {
        int words = 1 + ng_dim * ng_K / 16;
        auto ring = read_n<uint16_t>(in, words);
        auto bias = read_n<float>(in, ng_dim);
        auto exp = read_n<float>(in, ng_dim);
        std::vector<uint16_t> lutm(1u << 16);
        exl3_codebook_lut(Exl3Codebook::Mul1, lutm.data());
        std::vector<float> got(ng_dim);
        exl3_ngram_decode_row(ring.data(), ng_K, lutm.data(), ng_dim, bias.data(), got.data());
        double ne = rel_err(got, exp);
        std::printf("ngram ring decode rel_err: %.3e (limit 1e-4)\n", ne);
        if (!(ne < 1e-4)) ++fails;
    }

    std::printf("%s\n", fails ? "FAIL" : "OK");
    return fails ? 1 : 0;
}
