"""Inspect an Ornith / Qwen35MoE GGUF header without downloading the tensor data.

The model files are ~20 GB; only the GGUF header (metadata + tensor table) is
needed to record the architecture contract.  The header of these artifacts is
large because it carries the tokenizer vocabulary, so it is streamed from
Hugging Face with a plain HTTP GET and the connection is closed once the tensor
table has been parsed.

Usage:
    python tools/ornith_inspect.py --repo AtomicChat/Ornith-1.5-35B-A3B-GGUF \
        --file Ornith-1.5-35B-A3B-AD-Q4_K-IQ4_XS.gguf --out docs/ornith/gguf-layout.txt
    python tools/ornith_inspect.py --local /path/to/model.gguf --out ...

The output is plain text so a reviewer can diff two artifacts.
"""
from __future__ import annotations

import argparse
import io
import struct
import sys
import urllib.request
from collections import Counter, defaultdict

sys.path.insert(0, str(__import__("pathlib").Path(__file__).resolve().parent))
from gguf_reader import BLOCK_GEOMETRY, GGML_TYPES, GGUF_META  # noqa: E402


class _StreamReader:
    """Reads exactly the bytes requested from a live HTTP response."""

    def __init__(self, raw: io.BufferedReader):
        self._raw = raw;
        self.n = 0

    def read(self, n: int) -> bytes:
        b = self._raw.read(n)
        if len(b) != n:
            raise EOFError(f"short read: wanted {n}, got {len(b)}")
        self.n += len(b)
        return b

    def u32(self):
        return struct.unpack("<I", self.read(4))[0]

    def u64(self):
        return struct.unpack("<Q", self.read(8))[0]


def parse_header(r) -> tuple[dict, list[dict], int]:
    magic = r.u32()
    if magic != 0x46554747:
        raise SystemExit(f"not a GGUF file (magic {magic:#x})")
    version = r.u32()
    n_tensors = r.u64()
    n_kv = r.u64()
    if version != 3:
        raise SystemExit(f"GGUF v{version}, this reader handles v3")

    meta: dict = {}
    for _ in range(n_kv):
        key = _str(r)
        meta[key] = _value(r)
    tensors = []
    for _ in range(n_tensors):
        name = _str(r)
        n_dims = r.u32()
        shape = [r.u64() for _ in range(n_dims)]
        type_id = r.u32()
        offset = r.u64()
        tensors.append({"name": name, "shape": shape, "type_id": type_id,
                        "type_name": GGML_TYPES.get(type_id, f"type{type_id}"),
                        "offset": offset})

    # The data section starts after the tensor table, padded to the alignment.
    align = 32
    a = meta.get("general.alignment")
    if isinstance(a, int) and a:
        align = a
    data_start = (r.n + align - 1) // align * align
    return {"version": version, "n_tensors": n_tensors,
            "alignment": align, "data_start": data_start}, meta, tensors


def _str(r: _StreamReader) -> str:
    n = r.u64()
    return r.read(n).decode("utf-8", "replace")


def _value(r: _StreamReader):
    t = r.u32()
    name, size = GGUF_META[t]
    if name == "string":
        return _str(r)
    if name == "array":
        et = r.u32()
        count = r.u64()
        ename, esize = GGUF_META[et]
        if ename == "string":
            return [_str(r) for _ in range(count)]
        fmt = {"u8": "B", "i8": "b", "u16": "H", "i16": "h", "u32": "I", "i32": "i",
               "f32": "f", "bool": "?", "u64": "Q", "i64": "q", "f64": "d"}[ename]
        raw = r.read(esize * count)
        return list(struct.unpack(f"<{count}{fmt}", raw))
    fmt = {"u8": "B", "i8": "b", "u16": "H", "i16": "h", "u32": "I", "i32": "i",
           "f32": "f", "bool": "?", "u64": "Q", "i64": "q", "f64": "d"}[name]
    return struct.unpack(f"<{fmt}", r.read(size))[0]


def tensors_bytes(t: dict) -> int | None:
    geom = BLOCK_GEOMETRY.get(t["type_name"])
    if geom is None:
        return None
    elems = 1
    for d in t["shape"]:
        elems *= d
    be, bb = geom
    if elems % be:
        return None
    return elems // be * bb


# ----------------------------------------------------------------------------- report

def architecture_name(meta: dict) -> str:
    for k in ("general.architecture",):
        if k in meta:
            return str(meta[k])
    return "?"


def fmt_shape(shape: list[int]) -> str:
    return "[" + ", ".join(str(s) for s in shape) + "]"


def build_report(header: dict, meta: dict, tensors: list[dict], source: str) -> str:
    lines: list[str] = []
    w = lines.append

    arch = architecture_name(meta)
    w(f"# GGUF layout report: {source}")
    w(f"# generated by tools/ornith_inspect.py")
    w("")
    w(f"general.architecture        = {arch}")
    w(f"gguf.version                = {header['version']}")
    w(f"gguf.n_tensors              = {header['n_tensors']}")
    w(f"gguf.alignment              = {header['alignment']}")
    w(f"gguf.data_start             = {header['data_start']}")
    w("")

    # --- general + architecture scalar metadata, sorted for stability
    w("## metadata (non-tokenizer)")
    for k in sorted(meta):
        if k.startswith("tokenizer."):
            continue
        v = meta[k]
        if isinstance(v, list):
            if len(v) > 16:
                w(f"{k} = [array len={len(v)}]")
            else:
                w(f"{k} = {v}")
        else:
            w(f"{k} = {v}")
    w("")

    # --- tokenizer summary (the vocabulary itself is huge; summarize)
    w("## tokenizer metadata")
    for k in sorted(meta):
        if not k.startswith("tokenizer."):
            continue
        v = meta[k]
        if isinstance(v, list):
            w(f"{k} = [array len={len(v)}]")
        else:
            w(f"{k} = {v}")
    w("")

    # --- per-layer geometry derived from the well-known keys
    w("## derived geometry")
    def g(key, default=None):
        return meta.get(key, default)

    n_layer = None
    for cand in ("block_count",):
        if f"{arch}.{cand}" in meta:
            n_layer = meta[f"{arch}.{cand}"]
    w(f"{arch}.block_count = {n_layer}")
    for key in sorted(meta):
        if key.startswith(arch + ".") and "expert" in key:
            w(f"{key} = {meta[key]}")
    w("")

    # --- tensor type histogram
    w("## tensor type histogram")
    hist = Counter(t["type_name"] for t in tensors)
    for name, cnt in sorted(hist.items(), key=lambda kv: (-kv[1], kv[0])):
        w(f"{name:12s} {cnt}")
    w("")

    # --- group tensors by layer and by kind
    by_layer: dict[int, list[dict]] = defaultdict(list)
    non_layer: list[dict] = []
    for t in tensors:
        lay = None
        name = t["name"]
        for marker in ("blk.", "layers."):
            if marker in name:
                tail = name.split(marker, 1)[1]
                num = ""
                for ch in tail:
                    if ch.isdigit():
                        num += ch
                    else:
                        break
                if num:
                    lay = int(num)
                break
        if lay is None:
            non_layer.append(t)
        else:
            by_layer[lay].append(t)

    w("## non-layer tensors")
    for t in sorted(non_layer, key=lambda t: t["name"]):
        nb = tensors_bytes(t)
        nbs = f"{nb:>13d}" if nb is not None else "            ?"
        w(f"{t['name']:60s} {t['type_name']:8s} {fmt_shape(t['shape']):20s} bytes={nbs}")
    w("")

    w(f"## per-layer tensors ({len(by_layer)} layers)")
    for lay in sorted(by_layer):
        w(f"### layer {lay}")
        for t in sorted(by_layer[lay], key=lambda t: t["name"]):
            nb = tensors_bytes(t)
            nbs = f"{nb:>13d}" if nb is not None else "            ?"
            w(f"{t['name']:60s} {t['type_name']:8s} {fmt_shape(t['shape']):20s} bytes={nbs}")
        w("")

    # --- expert tensor types, by layer (the question Phase 5 asks)
    w("## expert tensor types by layer")
    expert_names = [t for t in tensors if "expert" in t["name"] or "ffn_"
                    in t["name"] or "feed_forward" in t["name"]]
    grouped: dict[str, list[tuple[int, str]]] = defaultdict(list)
    for t in expert_names:
        # strip the layer number to group the same logical tensor
        tail = t["name"]
        idx = None
        for marker in ("blk.", "layers."):
            if marker in tail:
                after = tail.split(marker, 1)[1]
                num = ""
                for ch in after:
                    if ch.isdigit():
                        num += ch
                    else:
                        break
                idx = int(num) if num else None
                tail = tail.split(marker, 1)[0] + marker + "N" + after[len(num):]
                break
        grouped[tail].append((idx if idx is not None else -1, t["type_name"]))
    for logical in sorted(grouped):
        items = sorted(grouped[logical])
        types = Counter(tp for _, tp in items)
        w(f"{logical:60s} n={len(items):3d} types={dict(types)}")

    w("")
    w("## routed-expert down/gate/up types per layer")
    for lay in sorted(by_layer):
        row = {}
        for t in by_layer[lay]:
            n = t["name"]
            if "expert" not in n:
                continue
            if n.endswith(".ffn_down.weight") or ".ffn_down" in n:
                row["down"] = t["type_name"]
            elif ".ffn_gate" in n:
                row["gate"] = t["type_name"]
            elif ".ffn_up" in n:
                row["up"] = t["type_name"]
        if row:
            w(f"layer {lay:3d}: {row}")

    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo")
    ap.add_argument("--file")
    ap.add_argument("--revision", default="main")
    ap.add_argument("--local")
    ap.add_argument("--out", required=True)
    ap.add_argument("--header-out", default=None,
                    help="also write the raw GGUF header (metadata + tensor table) to this file; the "
                         "result is openable by the engine's GgufFile since only the header is needed")
    args = ap.parse_args()

    if args.local:
        with open(args.local, "rb") as fh:
            r = _StreamReader(fh)
            header, meta, tensors = parse_header(r)
        source = args.local
    else:
        if not (args.repo and args.file):
            ap.error("--repo and --file, or --local")
        url = (f"https://huggingface.co/{args.repo}/resolve/{args.revision}/{args.file}")
        req = urllib.request.Request(url, headers={"User-Agent": "strata-ornith-inspect"})
        with urllib.request.urlopen(req, timeout=600) as resp:
            # wrap so read() is buffered; close after the tensor table
            r = _StreamReader(resp)  # type: ignore[arg-type]
            header, meta, tensors = parse_header(r)
        source = f"hf://{args.repo}/{args.file}@{args.revision}"

    report = build_report(header, meta, tensors, source)
    out = __import__("pathlib").Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(report)
    if args.header_out:
        # The header plus enough zero padding that data_start <= file size, so GgufFile opens it.  Tensor
        # data is never read; this is only the metadata + tensor directory.
        n = header["data_start"]
        if args.local:
            raw = open(args.local, "rb").read(n)
        else:
            url = f"https://huggingface.co/{args.repo}/resolve/{args.revision}/{args.file}"
            req = urllib.request.Request(url, headers={"Range": f"bytes=0-{n - 1}",
                                                       "User-Agent": "strata-ornith-inspect"})
            with urllib.request.urlopen(req, timeout=600) as resp:
                raw = resp.read()
        hp = __import__("pathlib").Path(args.header_out)
        hp.parent.mkdir(parents=True, exist_ok=True)
        hp.write_bytes(raw)
        print(f"wrote {hp} ({len(raw)} header bytes)")
    print(f"wrote {out} ({len(report)} bytes, {header['n_tensors']} tensors, "
          f"header {header['data_start']} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
