# One native backend. Dependencies are prepared explicitly before configure;
# there are no downloads during CMake or server startup.
set(STRATA_XGRAMMAR_DIR "" CACHE PATH "Pinned dependency from tools/prepare_xgrammar.py")
if(NOT EXISTS "${STRATA_XGRAMMAR_DIR}/PIN.json")
  message(FATAL_ERROR "GBNF needs: python tools/prepare_xgrammar.py --out <new-dir>, then -DSTRATA_XGRAMMAR_DIR=<new-dir>")
endif()
file(READ "${STRATA_XGRAMMAR_DIR}/PIN.json" _xg_pin)
string(JSON _xg_backend GET "${_xg_pin}" backend)
if(NOT _xg_backend STREQUAL "xgrammar-0.2.8-strata-budget1-json1")
  message(FATAL_ERROR "GBNF: unsupported XGrammar pin")
endif()
foreach(_file grammar_builder.cc fsm.cc earley_parser.h earley_parser.cc grammar_compiler.cc json_schema_converter.cc)
  string(JSON _wanted GET "${_xg_pin}" patched_files "cpp/${_file}" patched_sha256)
  file(SHA256 "${STRATA_XGRAMMAR_DIR}/cpp/${_file}" _got)
  if(NOT _wanted STREQUAL _got)
    message(FATAL_ERROR "GBNF dependency differs from the prepared pin: ${_file}")
  endif()
endforeach()
find_package(Threads REQUIRED)
# Upstream's native target has exactly these sources, excluding TVM bindings.
# Define that target here to avoid its global compiler flags and Python default.
file(GLOB_RECURSE _xg_sources CONFIGURE_DEPENDS "${STRATA_XGRAMMAR_DIR}/cpp/*.cc")
list(FILTER _xg_sources EXCLUDE REGEX "/cpp/tvm_ffi/.*\\.cc$")
add_library(strata_xgrammar STATIC ${_xg_sources})
target_compile_features(strata_xgrammar PUBLIC cxx_std_17)
target_include_directories(strata_xgrammar SYSTEM PUBLIC
  "${STRATA_XGRAMMAR_DIR}/include" "${STRATA_XGRAMMAR_DIR}/3rdparty/dlpack/include")
target_include_directories(strata_xgrammar SYSTEM PRIVATE "${STRATA_XGRAMMAR_DIR}/3rdparty/picojson")
target_include_directories(strata_xgrammar PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/include")
target_compile_definitions(strata_xgrammar PUBLIC XGRAMMAR_ENABLE_CPPTRACE=0 XGRAMMAR_ENABLE_INTERNAL_CHECK=0)
target_link_libraries(strata_xgrammar PUBLIC Threads::Threads)

add_library(strata_grammar STATIC src/core/grammar.cpp src/core/grammar_vocabulary.cpp)
target_include_directories(strata_grammar PUBLIC include)
target_include_directories(strata_grammar SYSTEM PRIVATE "${STRATA_XGRAMMAR_DIR}/3rdparty/picojson")
target_link_libraries(strata_grammar PUBLIC strata_xgrammar PRIVATE strata_warnings)
if(TARGET strata)
  target_link_libraries(strata PRIVATE strata_grammar)
  target_compile_definitions(strata PRIVATE STRATA_ENABLE_GBNF=1)
endif()
add_executable(grammar_native_test src/core/grammar_native_test.cpp)
target_link_libraries(grammar_native_test PRIVATE strata_grammar)
target_include_directories(grammar_native_test SYSTEM PRIVATE "${STRATA_XGRAMMAR_DIR}/3rdparty/picojson")
enable_testing()
add_test(NAME grammar_native_test COMMAND grammar_native_test
  "${CMAKE_CURRENT_SOURCE_DIR}/data/grammars/cases.json")
add_executable(grammar_inspection_test src/core/grammar_inspection_test.cpp)
target_link_libraries(grammar_inspection_test PRIVATE strata_grammar)
add_test(NAME grammar_inspection_test COMMAND grammar_inspection_test)
add_executable(grammar_speculation_test src/core/grammar_speculation_test.cpp)
target_link_libraries(grammar_speculation_test PRIVATE strata_grammar)
add_test(NAME grammar_speculation_test COMMAND grammar_speculation_test)
if(STRATA_ENABLE_CUDA OR STRATA_ENABLE_HIP)
  add_executable(grammar_speculation_gpu_test src/kernels/grammar_speculation_gpu_test.cpp)
  target_include_directories(grammar_speculation_gpu_test PRIVATE ${_strata_gpu_include_directories})
  target_link_libraries(grammar_speculation_gpu_test PRIVATE strata_grammar strata_kernels ${_strata_gpu_runtime_target})
  foreach(_sampler split one_block old)
    add_test(NAME grammar_speculation_${_sampler} COMMAND grammar_speculation_gpu_test)
  endforeach()
  set_tests_properties(grammar_speculation_split PROPERTIES ENVIRONMENT "STRATA_OLD_SAMPLER=0;STRATA_SAMPLER_ONE_BLOCK=0")
  set_tests_properties(grammar_speculation_one_block PROPERTIES ENVIRONMENT "STRATA_OLD_SAMPLER=0;STRATA_SAMPLER_ONE_BLOCK=1")
  set_tests_properties(grammar_speculation_old PROPERTIES ENVIRONMENT "STRATA_OLD_SAMPLER=1;STRATA_SAMPLER_ONE_BLOCK=0")
endif()
